### ISSUE TITLE
 Visual Representation for Issues

### ISSUE THREAD

**Issue by Uttkarsh-raj** [OWASP-BLT/BLT#3462]
#### Task List

- **Planning and Design**
  - [x] Define the visual data to be represented graphically.
  - [x] Design charts or graphs in Flutter for issue representation.

- **Development and Testing**
  - [x] Implement the visual representation using suitable Flutter libraries.
  - [x] Integrate APIs to fetch issues and plot data.
  - [x] Conduct user testing to refine visualizations.
